### ISSUE TITLE
Cant upload 1MB project.

### ISSUE THREAD

**Issue by bjorn-stromberg-codic** [Pingu1337/win21Upload#1]
https://win21.pingu.onl/Upload på denna sidan så försökte jag ladda upp
[node_modules.zip](https://github.com/Pingu1337/win21Upload/files/7951885/node_modules.zip)
men den verkar ha frusit 
![image](https://user-images.githubusercontent.com/67270174/151396020-cc535ce2-d6b4-484c-9ebb-212897e8aca8.png)

**Comment by Pingu1337** [comment]
This is now resolved.
